apiVersion: apps/v1
kind: Deployment
metadata:
  name: fcde
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fcde
  template:
    metadata:
      labels:
        app: fcde
    spec:
      containers:
      - image: okteto.dev/fcde:latest
        name: fcde
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "f84e81c1-f9d3-4a6e-928b-cdde07c85a3b"
        - name: Vless_Path
          value: "/cxsd4eswd"
        - name: Vmess_UUID
          value: "f84e81c1-f9d3-4a6e-928b-cdde07c85a3b"
        - name: Vmess_Path
          value: "/gfr4e3de"
        - name: Share_Path
          value: "/v2link"
